// Backlog semilla de temas para el generador de posts. Se inserta en la tabla
// blog_topics la primera vez (auto-seed en blog-topics-db.ts). Generado con un
// workflow multi-agente (10 categorías) y deduplicado contra los posts publicados.
// Ampliar esta lista (o insertar filas en blog_topics) cuando se agote.
export interface SeedTopic {
  title: string;
  targetKeyword?: string;
  angle?: string;
  internalLink?: string;
  category?: string;
  seasonMonth?: number; // 0 = atemporal, 1-12 = mes de mayor relevancia
  priority?: number; // 1-5
}

export const SEED_TOPICS: SeedTopic[] = [
  {
    title: "Cuánto facturar para ganar 2.000 € netos al mes siendo autónomo",
    targetKeyword: "cuánto facturar para 2000 euros netos autónomo",
    angle: "Tabla práctica que parte de objetivos de neto (1.500, 2.000, 3.000 €/mes) y trabaja hacia atrás: cuota RETA, IRPF estimado y gastos para deducir la facturación bruta mínima. Incluye escenarios con y sin tarifa plana.",
    internalLink: "/neto-bruto",
    category: "comparativas-decisiones",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Home office: cómo deducir el 30% de luz, agua y gas trabajando desde casa",
    targetKeyword: "deducir suministros autonomo casa",
    angle: "Aplicar la regla del 30% sobre el % de metros afectos (art. 30 LIRPF): ejemplo numérico con piso de 90 m2 y despacho de 18 m2. Distinguir suministros (regla 30%) de gastos de titularidad como IBI, comunidad o hipoteca (proporción directa de metros). Requisito previo: declarar los metros afectos en el alta censal (036/037).",
    internalLink: "/guias/gastos-deducibles",
    category: "gastos-deducibles",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Deducir el coche del autónomo en 2026: el 50% de IVA y el 100% que casi nadie consigue",
    targetKeyword: "deducir coche autonomo",
    angle: "Diferenciar el tratamiento de IVA (50% por defecto salvo prueba de afectación exclusiva) frente al IRPF (afectación total o nada, sin punto medio). Lista cerrada de actividades con 100% presunto (taxi, comercial, autoescuela, transporte) y cómo documentar el uso si no estás en ella.",
    internalLink: "/guias/gastos-deducibles",
    category: "gastos-deducibles",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Dietas y manutención del autónomo: los límites de 26,67 € y 53,34 € al día",
    targetKeyword: "dietas manutencion autonomo limite",
    angle: "Requisitos acumulativos de la deducción de manutención: en municipio distinto, pago electrónico obligatorio (no efectivo) y factura/justificante. Tope diario 26,67 € en España sin pernocta y 53,34 € con pernocta (el doble en extranjero). Aclarar que NO incluye comidas con el portátil al lado de casa.",
    internalLink: "/dietas-kilometraje",
    category: "gastos-deducibles",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Modelo 130 paso a paso: rellenar tu pago fraccionado del IRPF con ejemplo",
    targetKeyword: "como rellenar el modelo 130",
    angle: "Lo clave que casi nadie explica bien: el 130 es ACUMULATIVO (declaras del 1 de enero al cierre del trimestre, no solo 3 meses) y se resta lo ya pagado. Ejemplo numérico real casilla a casilla (01 ingresos, 02 gastos, 03 rendimiento, 04 el 20%, 07 reducción 100 euros/mes, 19 resultado) con un autónomo que en 1T paga y en 2T sale negativo a compensar. Incluye el test del 70% de ingresos con retención para saber si estás obligado.",
    internalLink: "/calculadora-irpf",
    category: "como-rellenar-modelos",
    seasonMonth: 4,
    priority: 5,
  },
  {
    title: "Modelo 303 de IVA 2026 casilla a casilla (con la nueva casilla 112)",
    targetKeyword: "como rellenar el modelo 303 2026",
    angle: "Actualizado a la Orden HAC/27/2026: explica la novedad de la casilla 112 (pago a cuenta de carburantes) y los cambios del SII desde febrero, además del recorrido estándar de IVA devengado vs deducible y casilla 71 (resultado). Ejemplo de un freelance con facturas al 21% y gastos deducibles. Diferencia clave: a quién afecta de verdad la casilla 112 y a quién no.",
    internalLink: "/calculadora-iva",
    category: "como-rellenar-modelos",
    seasonMonth: 7,
    priority: 5,
  },
  {
    title: "Modelo 036 vs 037 para darte de alta: cuál marcar y cómo rellenarlo",
    targetKeyword: "como rellenar el modelo 037 alta autonomo",
    angle: "Guía del alta express con las 4 casillas que cubren el 95% de los casos (111 alta, 502 estimación directa simplificada, 600 IVA general, 700 pagos fraccionados IRPF) y cómo elegir el epígrafe IAE sin equivocarte. Incluye cuándo el 037 simplificado (3 páginas) te basta y cuándo estás obligado al 036 (operaciones intracomunitarias, regímenes especiales).",
    internalLink: "/guias/alta-autonomo",
    category: "como-rellenar-modelos",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Cómo cambiar de tramo de cotización en 6 pasos (Import@ss)",
    targetKeyword: "cambiar base de cotización autónomo 2026",
    angle: "Tutorial operativo con las 6 ventanas de cambio del año (1 ene, 1 mar, 1 may, 1 jul, 1 sep, 1 nov), capturas del trámite y cuándo entra en vigor cada cambio. No es teoría de tramos, es el cómo se hace.",
    internalLink: "/cuota-autonomo",
    category: "cuota-cotizacion",
    seasonMonth: 2,
    priority: 5,
  },
  {
    title: "Regularización de la cuota de autónomos: por qué Hacienda te devuelve o reclama",
    targetKeyword: "regularización cuota autónomos cómo funciona",
    angle: "Explica el cruce de tu cuota provisional con tu rendimiento real declarado en la Renta, con 2 ejemplos numéricos (uno que recibe devolución de la TGSS y otro al que le reclaman), plazos y qué hacer si no estás de acuerdo.",
    internalLink: "/cuota-autonomo",
    category: "cuota-cotizacion",
    seasonMonth: 9,
    priority: 5,
  },
  {
    title: "Cómo calcular tu rendimiento neto para elegir tramo de cuota RETA",
    targetKeyword: "cómo calcular rendimiento neto autónomo",
    angle: "Fórmula exacta: ingresos menos gastos deducibles, menos cuotas RETA, menos el 7% (3% societarios) de deducción por gastos genéricos, dividido entre 12. Con ejemplo completo para acertar el tramo y evitar regularización.",
    internalLink: "/cuota-autonomo",
    category: "cuota-cotizacion",
    seasonMonth: 1,
    priority: 5,
  },
  {
    title: "Cotizar por más para mejorar la pensión: ¿compensa subir la base?",
    targetKeyword: "cotizar más autónomo mejor pensión",
    angle: "Cálculo de retorno: cuánto sube la pensión por cada 100 € extra de base, el efecto de los últimos 25 años de cómputo y a partir de qué edad empieza a compensar subir la base. Compara el sobrecoste mensual frente a invertir esa diferencia por tu cuenta. Tabla coste vs beneficio.",
    internalLink: "/jubilacion-autonomo",
    category: "cuota-cotizacion",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Capitalizar el paro para hacerte autónomo en 2026: pago único paso a paso",
    targetKeyword: "capitalizar el paro para autónomo 2026",
    angle: "Guía operativa del pago único del SEPE: cuándo conviene cobrar el 100% para inversión vs reservar parte para pagar cuotas mensuales, requisitos (no haberlo cobrado en 4 años), plazos (solicitar ANTES del alta), y compatibilidad con la tarifa plana de 88,64 €. Tabla de errores que tumban la solicitud.",
    internalLink: "/guias/alta-autonomo",
    category: "altas-bajas-prestaciones",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Cese de actividad: requisitos y cuánto cobra el paro del autónomo en 2026",
    targetKeyword: "paro del autónomo cese de actividad 2026",
    angle: "Desmontar el mito de que el autónomo no tiene paro. Requisitos reales (12 meses cotizados mínimo, situación legal de cese, pérdidas >10% o deudas), tabla de duración según meses cotizados (4 a 24 meses), cuantía (70% de la base reguladora) y por qué casi nadie lo cobra: los errores que provocan denegación.",
    internalLink: "/cuota-autonomo",
    category: "altas-bajas-prestaciones",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Retención IRPF en factura: 15%, 7%, 2% o 1%, cuál te toca",
    targetKeyword: "que retencion poner en factura autonomo",
    angle: "Árbol de decisión práctico: nuevo autónomo (7% los 3 primeros años) vs general (15%), módulos (1%), actividades agrarias/forestales (2%). Casos reales por epígrafe IAE y cómo cambiar del 7 al 15 a tiempo para no quedarte corto en la Renta.",
    internalLink: "/retencion-irpf-facturas",
    category: "irpf-retenciones",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Autónomo vs SL en 2026: a partir de qué beneficio compensa el cambio",
    targetKeyword: "cuando pasar de autonomo a sl 2026",
    angle: "Análisis del punto de equilibrio real (umbral 40.000-50.000 € de beneficio) comparando IRPF progresivo del autónomo frente al 23% del Impuesto de Sociedades para pymes, con ejemplos numéricos a 30k, 45k y 70k de beneficio.",
    internalLink: "/sl-vs-autonomo",
    category: "comparativas-decisiones",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Vender servicios a empresas de la UE: ROI, NIF-IVA y modelo 349 paso a paso",
    targetKeyword: "iva intracomunitario autonomo modelo 349",
    angle: "Guía operativa del autónomo de servicios (no e-commerce): alta en el ROI con el modelo 036, obtención del NIF-IVA (ES + NIF), por qué hay que verificar al cliente en VIES y guardar la captura, facturar sin IVA con inversión del sujeto pasivo del cliente, y declarar en el modelo 349 (mensual salvo que no superes 50.000 €). Diferenciar de las adquisiciones intracomunitarias.",
    internalLink: "/iva-plataformas-internacionales",
    category: "iva-regimenes",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "OSS y modelo 369: cómo declarar el IVA si vendes servicios digitales en la UE",
    targetKeyword: "modelo 369 oss servicios digitales",
    angle: "Centrado en el B2C digital: el umbral común de 10.000 €/año en ventas a particulares UE, qué cambia al superarlo (aplicar el IVA del país del cliente), alta voluntaria con el modelo 035 y declaración trimestral con el modelo 369 desde España, sin tener que registrarse país por país. Ejemplo con un infoproducto vendido a Francia y Alemania.",
    internalLink: "/iva-plataformas-internacionales",
    category: "iva-regimenes",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Factura electrónica B2B obligatoria: cuándo te toca según el RD 238/2026",
    targetKeyword: "factura electronica obligatoria autonomos",
    angle: "Desglose del calendario real del RD 238/2026: facturación >8M euros desde octubre 2027 y el resto de empresas y autónomos desde octubre 2028, separando claramente esta obligación de Verifactu (son cosas distintas) y explicando qué exige cada una.",
    internalLink: "/verifactu",
    category: "facturacion-digital",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Kit Digital 2026 para autónomos: hasta 2.000 euros para tu software de facturación",
    targetKeyword: "kit digital 2026 autonomos",
    angle: "Estado real tras la Orden TDF/39/2026: programa reactivado, autónomos elegibles desde 6 meses de antigüedad, sin fecha límite fija (hasta agotar fondos), cuantía de 2.000 euros del Segmento III y cómo destinarla a un software de facturación que ya cumpla Verifactu.",
    internalLink: "/verifactu",
    category: "facturacion-digital",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Fiscalidad del programador freelance: IVA en clientes UE y Reverse Charge",
    targetKeyword: "iva programador freelance clientes extranjero",
    angle: "Caso práctico de un dev que factura a un cliente alemán y otro estadounidense: cuándo va con IVA, cuándo sin (inversión del sujeto pasivo), alta en ROI y modelo 349. Tabla por tipo de cliente y país.",
    internalLink: "/iva-plataformas-internacionales",
    category: "guias-sector",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Impuestos del creador de contenido: cómo tributan Twitch, YouTube y patrocinios",
    targetKeyword: "impuestos creador de contenido streamer influencer",
    angle: "Desglose por fuente de ingreso (AdSense Irlanda, Twitch, regalos/donaciones, canjes de productos como ingreso en especie, colaboraciones con marcas) y el IVA de cada una. Aclara el ingreso en especie de productos gratis.",
    internalLink: "/iva-plataformas-internacionales",
    category: "guias-sector",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Fiscalidad del alquiler turístico Airbnb: IVA, IRPF y modelo 179",
    targetKeyword: "fiscalidad airbnb autonomo iva irpf",
    angle: "La frontera clave: alquiler de vivienda exento de IVA vs alquiler con servicios tipo hotel (limpieza diaria, desayuno) que sí lleva 10% IVA y obliga al alta de autónomo. Incluye el modelo 179 informativo de las plataformas.",
    internalLink: "/calculadora-iva",
    category: "guias-sector",
    seasonMonth: 5,
    priority: 5,
  },
  {
    title: "Ecommerce y dropshipping: IVA OSS, importaciones y umbral de los 10.000 €",
    targetKeyword: "iva ecommerce dropshipping autonomo oss",
    angle: "Régimen de ventas a distancia: umbral único de 10.000 € para toda la UE, alta en la ventanilla OSS y cómo declarar el IVA del país del cliente. Para dropshipping desde China: IVA de importación y el fin de la exención de los envíos de bajo valor.",
    internalLink: "/iva-plataformas-internacionales",
    category: "guias-sector",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Paralela de Hacienda: qué es y cómo responder paso a paso",
    targetKeyword: "paralela hacienda autonomo",
    angle: "Explicar la liquidación paralela del IRPF/IVA en lenguaje claro: por qué llega (descuadre con datos de terceros, retenciones, modelo 347), los plazos de 10/15 días hábiles para alegaciones, cómo presentar conformidad o disconformidad y los recargos asociados. Incluir plantilla mental de respuesta y cuándo conviene un asesor.",
    internalLink: "/retencion-irpf-facturas",
    category: "errores-inspecciones",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Recargos por presentar un modelo fuera de plazo en 2026 (5-15-20%)",
    targetKeyword: "recargo presentacion fuera de plazo autonomos",
    angle: "Desglosar el sistema de recargos por extemporaneidad del art. 27 LGT vigente: 1% + 1% por cada mes de retraso hasta el mes 12, 15% a partir de los 12 meses, más intereses de demora. Diferenciar recargo (presentas tú) de sanción (te pilla Hacienda) y la reducción del 25% por pronto pago. Ejemplos numéricos con el modelo 130 y 303.",
    internalLink: "/calendario-fiscal",
    category: "errores-inspecciones",
    seasonMonth: 1,
    priority: 5,
  },
  {
    title: "10 gastos que deduces mal y por los que Hacienda te puede sancionar",
    targetKeyword: "gastos mal deducidos autonomos sancion",
    angle: "Lista de los gastos que más rechaza Hacienda en autónomos: comidas sin afectación a la actividad, gasolina del coche al 100%, ropa, móvil personal, formación no relacionada, gastos del cónyuge. Para cada uno: el criterio AEAT/TEAC actual y cómo deducirlo bien (afectación, factura completa, medio de pago).",
    internalLink: "/guias/gastos-deducibles",
    category: "errores-inspecciones",
    seasonMonth: 0,
    priority: 5,
  },
  {
    title: "Seguros del autónomo deducibles: salud (hasta 500 €), RC, baja y vida",
    targetKeyword: "seguros deducibles autonomo",
    angle: "Tabla por tipo de seguro: salud privada deducible hasta 500 €/año por el titular y por familiar (1.500 € con discapacidad), responsabilidad civil y seguro del local 100%, seguro de baja/incapacidad como gasto vs. reducción, y el matiz del seguro de vida (normalmente no deducible salvo ligado a préstamo del negocio).",
    internalLink: "/baja-medica",
    category: "gastos-deducibles",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Móvil e internet del autónomo: por qué Hacienda casi siempre rechaza el 100%",
    targetKeyword: "deducir movil internet autonomo",
    angle: "El criterio de uso mixto: sin línea separada exclusiva profesional, Hacienda tiende a admitir un porcentaje parcial y rechazar el 100%. Solución práctica: segunda línea solo profesional para deducir íntegro. Diferencia entre IVA (deducible según afectación) e IRPF. Errores típicos en inspección.",
    internalLink: "/calculadora-iva",
    category: "gastos-deducibles",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Gastos de coche sin deducir la compra: gasolina, parking, peajes y seguro",
    targetKeyword: "deducir gasolina autonomo",
    angle: "Centrado solo en gastos de funcionamiento (combustible, mantenimiento, ITV, parking, peajes, seguro del coche). Explicar que en IRPF dependen de la afectación del vehículo, pero que el kilometraje y dietas en desplazamiento siguen otra regla. Tabla con tickets que SÍ valen y los que Hacienda tumba.",
    internalLink: "/dietas-kilometraje",
    category: "gastos-deducibles",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Modelo 111: cómo declarar las retenciones de tus facturas de profesionales",
    targetKeyword: "como rellenar el modelo 111 autonomo",
    angle: "El ángulo poco cubierto: el 111 NO es solo para quien tiene trabajadores. Si recibes una factura de otro autónomo con retención del 15% o 7%, eres tú quien la ingresa a Hacienda. Detalla casillas 07-08-09 (profesionales) frente a 01-02-03 (nóminas), con ejemplo de un freelance que solo paga a su gestor.",
    internalLink: "/retencion-irpf-facturas",
    category: "como-rellenar-modelos",
    seasonMonth: 4,
    priority: 4,
  },
  {
    title: "Modelo 100 (Renta): cómo declarar tus rendimientos de actividad económica",
    targetKeyword: "como declarar actividad economica renta autonomo",
    angle: "Recorrido por el bloque de rendimientos de actividades económicas en estimación directa dentro de Renta WEB: dónde van ingresos y gastos, cómo se trasladan los pagos fraccionados del 130 ya ingresados y las retenciones soportadas para que no pagues dos veces. Ejemplo de cómo cuadra lo declarado en los cuatro 130 con la Renta anual.",
    internalLink: "/calculadora-irpf",
    category: "como-rellenar-modelos",
    seasonMonth: 5,
    priority: 4,
  },
  {
    title: "Modelo 390: cómo rellenar el resumen anual de IVA y que cuadre con tus 303",
    targetKeyword: "como rellenar el modelo 390 resumen anual iva",
    angle: "El 390 no se paga, pero es donde Hacienda detecta descuadres: explica cómo la suma de tus cuatro 303 debe coincidir con el desglose anual, las casillas de prorrata y operaciones no sujetas, y quién está exento de presentarlo. Checklist para cuadrar antes del 30 de enero.",
    internalLink: "/calendario-fiscal",
    category: "como-rellenar-modelos",
    seasonMonth: 1,
    priority: 4,
  },
  {
    title: "Pluriactividad: cómo recuperar el exceso de cotización si trabajas por cuenta ajena y propia",
    targetKeyword: "devolución exceso cotización pluriactividad",
    angle: "Umbral de devolución actualizado 2026, porcentaje que devuelve la TGSS (50%/40%), si es automática o hay que pedirla y plazo de solicitud. Incluye la base reducida que puede elegir el pluriactivo en su primer año y cuándo conviene mantener o bajar el alta.",
    internalLink: "/pluriactividad",
    category: "cuota-cotizacion",
    seasonMonth: 5,
    priority: 4,
  },
  {
    title: "Autónomo colaborador: cuota, requisitos y diferencias con el familiar contratado",
    targetKeyword: "autónomo colaborador cuota requisitos",
    angle: "Quién puede serlo (cónyuge y familiares hasta 2º grado conviviendo), por qué cotiza por base mínima sin elegir tramo por ingresos, bonificaciones disponibles y por qué tributa en IRPF aunque no emita facturas.",
    internalLink: "/preguntas-frecuentes-autonomos",
    category: "cuota-cotizacion",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Autónomo societario 2026: por qué pagas 448 € de cuota y la base mínima de 1.424 €",
    targetKeyword: "cuota autonomo societario 2026",
    angle: "Explica la base mínima propia del societario (1.424,40 €, cuota ~448 €/mes en 2026), por qué no se rige por los tramos de ingresos reales del autónomo persona física, y cómo encaja esa cuota en la decisión de tener una SL. Compara coste anual societario vs persona física.",
    internalLink: "/cuota-autonomo-societario",
    category: "cuota-cotizacion",
    seasonMonth: 1,
    priority: 4,
  },
  {
    title: "Me equivoqué de tramo de cuota: cómo corregirlo antes de la regularización",
    targetKeyword: "corregir tramo cotización equivocado autónomo",
    angle: "Qué pasa si previste de menos (te reclamarán) o de más (recuperas), cómo recalcular a mitad de año si tu facturación cambia y aprovechar la siguiente ventana de cambio para ajustar y minimizar el ajuste de la regularización.",
    internalLink: "/cuota-autonomo",
    category: "cuota-cotizacion",
    seasonMonth: 6,
    priority: 4,
  },
  {
    title: "Baja médica de autónomo por enfermedad: desde qué día cobras y cuánto en 2026",
    targetKeyword: "baja medica autonomo cuanto se cobra",
    angle: "Calendario exacto del cobro: nada del día 1-3, 60% de la base reguladora del día 4 al 20, 75% desde el día 21 (enfermedad común); en accidente laboral el 75% desde el día siguiente. La cuota se sigue pagando salvo bonificación a partir del día 61. Diferencia entre contingencias comunes y profesionales y por qué importa qué mutua tienes.",
    internalLink: "/baja-medica",
    category: "altas-bajas-prestaciones",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Baja por maternidad siendo autónoma: cuánto cobras y cómo se calcula en 2026",
    targetKeyword: "baja maternidad autónoma cuanto cobra 2026",
    angle: "Cálculo del 100% de la base reguladora durante 16 semanas, la bonificación del 100% de la cuota durante el descanso (tarifa cero efectiva), compatibilidad con la tarifa plana al reincorporarse, y la bonificación por reincorporación tras la maternidad. Diferencia clave: la cuantía depende de TU base de cotización elegida, no de tus ingresos.",
    internalLink: "/baja-medica",
    category: "altas-bajas-prestaciones",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Jubilación activa del autónomo 2026: cobra el 100% de la pensión y sigue facturando",
    targetKeyword: "jubilacion activa autonomo 2026",
    angle: "La reforma de la jubilación activa 2025-2026: el porcentaje de pensión compatible ya no es fijo del 50%, sube según años cotizados tras la edad legal (hasta el 100% al cuarto año). Requisitos, cómo afecta tener trabajadores a cargo, la cuota reducida que paga el jubilado activo y comparación rápida con la jubilación demorada.",
    internalLink: "/jubilacion-autonomo",
    category: "altas-bajas-prestaciones",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Reducción del 20% por inicio de actividad: requisitos 2026",
    targetKeyword: "reduccion inicio actividad autonomo irpf",
    angle: "Quién puede aplicar el 20% de reducción en estimación directa (no haber tenido actividad el año anterior), el límite de 100.000 euros de base, los dos ejercicios que cuentan y errores que la AEAT regulariza. Diferencia con la tarifa plana de cuota.",
    internalLink: "/guias/tarifa-plana",
    category: "irpf-retenciones",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Plan de pensiones autónomo 2026: cuánto desgrava de verdad y el PPES",
    targetKeyword: "plan de pensiones autonomo desgravacion 2026",
    angle: "Límites reales 2026: 1.500 euros plan individual + hasta 4.250 euros extra en planes de empleo simplificados de autónomos (PPES). Simulación de ahorro fiscal según tu tramo marginal y por qué el PPES es la jugada infrautilizada del colectivo.",
    internalLink: "/jubilacion-autonomo",
    category: "irpf-retenciones",
    seasonMonth: 11,
    priority: 4,
  },
  {
    title: "Deducciones autonómicas en la Renta: las que olvidan los autónomos",
    targetKeyword: "deducciones autonomicas renta autonomo",
    angle: "Repaso por CCAA de deducciones que el autónomo suele pasar por alto: alquiler de vivienda, gastos de guardería, autoempleo/inicio de actividad (Madrid, Andalucía, etc.), zonas despobladas. Dónde mirar en Renta Web y cómo no perderlas por desconocimiento.",
    internalLink: "/calculadora-irpf",
    category: "irpf-retenciones",
    seasonMonth: 5,
    priority: 4,
  },
  {
    title: "Estimación directa vs módulos: qué IRPF pagas y qué régimen te conviene en 2026",
    targetKeyword: "estimacion directa o modulos autonomo",
    angle: "Comparativa práctica 2026 por actividad (transporte, hostelería, comercio): cómo se calcula el rendimiento en cada régimen, el 5% de gastos de difícil justificación (tope 2.000 euros) en directa, la retención del 1% en módulos y para qué perfiles compensa cada uno. Plazo de renuncia en diciembre con efecto al año siguiente.",
    internalLink: "/guias/gastos-deducibles",
    category: "irpf-retenciones",
    seasonMonth: 12,
    priority: 4,
  },
  {
    title: "Recargo de equivalencia 2026: tipos (5,2% / 1,4% / 0,5%) y a quién obliga",
    targetKeyword: "recargo de equivalencia 2026",
    angle: "Explicar el régimen desde la óptica del autónomo del comercio al por menor: tabla de recargos vigentes (5,2% IVA general, 1,4% reducido, 0,5% superreducido, 0,62% para el 5%), qué actividades quedan fuera (servicios, mayoristas, joyerías, gasolineras) y por qué no se presenta modelo 303 pero el IVA no es deducible. Incluir ejemplo numérico de una compra a proveedor y los errores que más sanciona Hacienda.",
    internalLink: "/calculadora-iva",
    category: "iva-regimenes",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Régimen de módulos 2026: límites 250.000/125.000 € prorrogados y cuándo te excluyen",
    targetKeyword: "limites modulos 2026",
    angle: "Aterrizar la prórroga del RD-ley 2/2026 y la Orden HAC/1425/2025: límites de exclusión (250.000 € totales / 125.000 € facturado a empresas), cómo funciona el régimen simplificado de IVA por módulos frente al 303 normal, y el efecto de superar el umbral (paso a estimación directa). Pensado para hostelería, transporte, construcción.",
    internalLink: "/calculadora-iva",
    category: "iva-regimenes",
    seasonMonth: 12,
    priority: 4,
  },
  {
    title: "Inversión del sujeto pasivo: cuándo emitir una factura sin IVA (art. 84 LIVA)",
    targetKeyword: "factura inversion del sujeto pasivo",
    angle: "Listar los casos prácticos más habituales para autónomos (ejecuciones de obra en construcción/rehabilitación entre empresas, móviles/consolas/portátiles a revendedores, materiales de recuperación, oro), la mención legal obligatoria del art. 84.Uno.2.º de la Ley 37/1992 en la factura, y cómo declararlo tanto emisor como receptor en el modelo 303 y resumen anual.",
    internalLink: "/generador-facturas",
    category: "iva-regimenes",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Adquisiciones intracomunitarias: cómo desgravar el IVA al comprar a proveedores de la UE",
    targetKeyword: "adquisiciones intracomunitarias iva",
    angle: "El lado de la compra (no la venta): por qué Google/Meta/Stripe te facturan sin IVA, el mecanismo de autorepercusión (declaras IVA devengado y deducible a la vez en el modelo 303, neutro si tienes derecho a deducción total), la necesidad de estar en el ROI, y cómo recoger estas operaciones en el modelo 349. Ejemplo con una factura de publicidad de 300 €.",
    internalLink: "/calculadora-iva",
    category: "iva-regimenes",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Tarifa por hora vs precio por proyecto: qué te deja más neto",
    targetKeyword: "tarifa por hora o por proyecto autonomo",
    angle: "Compara los dos modelos desde la rentabilidad real por hora trabajada, incluyendo horas no facturables, riesgo de scope creep y cómo calcular tu tarifa hora mínima a partir de tu objetivo de neto anual.",
    internalLink: "/tarifa-hora-vs-proyecto",
    category: "comparativas-decisiones",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Pluriactividad: ¿compensa seguir de autónomo si tienes nómina?",
    targetKeyword: "pluriactividad autonomo y asalariado merece la pena",
    angle: "Analiza las bonificaciones y la devolución por exceso de cotización en pluriactividad, compara el coste neto real de mantener el alta frente a los ingresos extra y cuándo conviene darse de baja o reducir la base.",
    internalLink: "/pluriactividad",
    category: "comparativas-decisiones",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Factura rectificativa: cuándo es obligatoria y por qué NUNCA debes borrar una factura",
    targetKeyword: "factura rectificativa autonomo",
    angle: "Diferencia entre rectificar por sustitución y por diferencias, serie y numeración propia de las rectificativas, referencia obligatoria a la factura original, y el aviso clave: borrar una factura rompe la correlatividad, Verifactu lo detecta y puede sancionarse hasta 50.000 euros.",
    internalLink: "/generador-facturas",
    category: "facturacion-digital",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Numeración y series de facturas: cómo evitar el error que te detecta Verifactu",
    targetKeyword: "numeracion facturas autonomo series",
    angle: "Reglas de correlatividad sin saltos ni repeticiones dentro de cada serie, cuándo conviene usar series separadas (ordinarias F, rectificativas R, distintos negocios), reinicio anual de numeración y por qué con Verifactu cualquier hueco es una bandera roja para Hacienda.",
    internalLink: "/generador-facturas",
    category: "facturacion-digital",
    seasonMonth: 1,
    priority: 4,
  },
  {
    title: "Factura proforma vs factura simplificada vs factura ordinaria: cuál emitir y cuándo",
    targetKeyword: "factura proforma vs factura",
    angle: "Comparativa de los tres documentos: la proforma no tiene valor fiscal ni genera IVA (es presupuesto), la simplificada vale hasta 400 euros (3.000 en hostelería/comercio) pero no permite deducir IVA al cliente, y cuándo estás obligado a emitir factura completa con todos los datos.",
    internalLink: "/generador-facturas",
    category: "facturacion-digital",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Cómo facturar a un cliente fuera de la UE (exportación de servicios) siendo autónomo",
    targetKeyword: "facturar cliente extranjero fuera UE",
    angle: "Reglas de localización para servicios a clientes fuera de la UE: cuándo la operación queda no sujeta a IVA español, qué mención poner en la factura, cómo afecta a la retención de IRPF (un pagador extranjero no retiene pero el ingreso sí tributa en tu Renta) y dónde declararlo, diferenciándolo del régimen intracomunitario.",
    internalLink: "/iva-plataformas-internacionales",
    category: "facturacion-digital",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Gastos deducibles del transportista autónomo: combustible, dietas y vehículo",
    targetKeyword: "gastos deducibles transportista autonomo",
    angle: "El IVA del vehículo industrial afecto 100% (camión, furgoneta) se deduce íntegro frente al turismo al 50%. Combustible, peajes, reparaciones, dietas en ruta y la amortización del vehículo. Enlaza con calculadora de dietas y kilometraje.",
    internalLink: "/dietas-kilometraje",
    category: "guias-sector",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Autónomo fisioterapeuta: cuándo tu actividad sanitaria está exenta de IVA",
    targetKeyword: "fisioterapeuta autonomo iva exento",
    angle: "La exención sanitaria del artículo 20 LIVA: tratamientos con finalidad terapéutica exentos vs servicios de bienestar/estética y venta de productos que sí llevan 21%. Implica que no puede deducir el IVA soportado. Caso de consulta mixta.",
    internalLink: "/calculadora-iva",
    category: "guias-sector",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Profesor y formador online: IVA de la enseñanza exento vs cursos grabados",
    targetKeyword: "iva formacion online profesor autonomo",
    angle: "La exención educativa de la LIVA aplica a la enseñanza reglada y clases particulares de materias del plan de estudios, pero los cursos online automatizados/grabados se consideran servicios electrónicos con IVA 21% y reglas de localización OSS. Tabla clase en directo vs curso grabado vs membresía.",
    internalLink: "/calculadora-iva",
    category: "guias-sector",
    seasonMonth: 9,
    priority: 4,
  },
  {
    title: "Requerimiento de Hacienda: cómo responderlo y plazos para no liarla",
    targetKeyword: "como responder requerimiento hacienda autonomo",
    angle: "Guía operativa: tipos de requerimiento (informativo, de comprobación, inicio de procedimiento), el plazo de 10 días hábiles, cómo presentar la documentación por la Sede Electrónica, qué NO decir de más, y las consecuencias de ignorarlo (sanción por resistencia art. 203 LGT). Diferencia entre requerimiento y inicio de inspección.",
    internalLink: "/preguntas-frecuentes-autonomos",
    category: "errores-inspecciones",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Sanciones de Hacienda a autónomos: cuáles son y cómo reducirlas hasta un 65%",
    targetKeyword: "sanciones hacienda autonomos reduccion",
    angle: "Tabla práctica de infracciones tributarias (leve, grave, muy grave) y sus porcentajes: dejar de ingresar, presentar incorrecto, no atender requerimientos. Foco en las reducciones acumulables tras la reforma: 30% por conformidad + 40% por pronto pago sin recurrir, que suman hasta un 65% de rebaja. Cómo decidir si recurrir o aceptar.",
    internalLink: "/cuota-autonomo",
    category: "errores-inspecciones",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Discrepancia IVA repercutido vs ingresos en IRPF: el descuadre que te delata",
    targetKeyword: "descuadre iva irpf hacienda autonomo",
    angle: "Explicar el cruce automático que hace la AEAT entre la base imponible del 303 anual y los ingresos del 130/100, por qué surgen descuadres legítimos (operaciones exentas, inversión del sujeto pasivo, criterio de caja vs devengo) y cómo cuadrarlos antes de presentar para no recibir una propuesta de liquidación.",
    internalLink: "/calculadora-iva",
    category: "errores-inspecciones",
    seasonMonth: 1,
    priority: 4,
  },
  {
    title: "Prescripción fiscal: cuántos años puede revisarte Hacienda (4 vs 10)",
    targetKeyword: "prescripcion fiscal autonomos años",
    angle: "Aclarar la confusión entre el plazo de prescripción de 4 años para liquidar deudas (art. 66 LGT) y los 10 años para comprobar bases o cuotas compensadas y créditos fiscales (art. 66 bis). Cuándo se interrumpe la prescripción (un requerimiento la reinicia), desde cuándo cuenta cada modelo y cuántos años conviene guardar facturas en la práctica.",
    internalLink: "/generador-facturas",
    category: "errores-inspecciones",
    seasonMonth: 0,
    priority: 4,
  },
  {
    title: "Amortización para autónomos: cómo deducir el ordenador, el móvil o la moto poco a poco",
    targetKeyword: "amortizacion autonomo ordenador",
    angle: "Cuándo un bien va a gasto directo (importe bajo, criterio práctico hasta 300 € por elemento) y cuándo hay que amortizarlo por tablas. Coeficientes lineales máximos vigentes (equipos informáticos 25%, mobiliario 10%, vehículos 16%) con ejemplo de un portátil de 1.200 €. Mención a libertad de amortización para empresas de reducida dimensión.",
    internalLink: "/calculadora-irpf",
    category: "gastos-deducibles",
    seasonMonth: 0,
    priority: 3,
  },
  {
    title: "Mínimos personal y familiar: cuánto IRPF te ahorran los hijos",
    targetKeyword: "minimo por descendientes irpf 2026",
    angle: "Cifras 2026: mínimo personal 5.550 euros, por descendientes (2.400/2.700/4.000/4.500 en escalera) y ascendientes mayores de 65. Cómo afectan al autónomo en estimación directa y por qué reducen cuota pero no son una deducción directa.",
    internalLink: "/calculadora-irpf",
    category: "irpf-retenciones",
    seasonMonth: 4,
    priority: 3,
  },
  {
    title: "Gestoría vs hacerlo tú mismo: cuándo sale rentable cada opción",
    targetKeyword: "gestoria o hacerlo yo mismo autonomo",
    angle: "Compara coste de gestoría (40-80 €/mes) frente al valor de tu tiempo y al riesgo de errores y sanciones, con un árbol de decisión por perfil: sin IVA intracomunitario, con nóminas, con módulos, etc. Punto de inflexión donde compensa externalizar.",
    internalLink: "/preguntas-frecuentes-autonomos",
    category: "comparativas-decisiones",
    seasonMonth: 0,
    priority: 3,
  },
  {
    title: "Formación, cursos y máster: cuándo son gasto deducible y cuándo no",
    targetKeyword: "deducir formacion cursos autonomo",
    angle: "El criterio de correlación con los ingresos: la formación debe estar vinculada a la actividad ya ejercida, no a una futura distinta. Casos reales: un diseñador deduce un curso de UX (sí) pero no un máster de fotografía si no factura como fotógrafo. Tratamiento de libros, congresos y suscripciones profesionales.",
    internalLink: "/guias/gastos-deducibles",
    category: "gastos-deducibles",
    seasonMonth: 9,
    priority: 3,
  },
];
